# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, null=True)),
                ('Description', models.CharField(max_length=4800, null=True)),
                ('Due_Date', models.DateField(null=True)),
                ('Status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=120, null=True)),
                ('Description', models.CharField(max_length=4800, null=True)),
                ('Due_Date', models.DateField(null=True)),
                ('Status', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='subtask',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.task'),
        ),
    ]
