# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-14 14:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='Status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Status',
        ),
    ]
